# Generated by Django 3.1.7 on 2021-05-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
