# Generated by Django 3.1.7 on 2021-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_employee_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.CharField(default='anything', max_length=10),
        ),
    ]
